swagger: "2.0"
################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "0.0.1"
  title: RJ Product Information Facade
# during dev, should point to your local machine
################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: 130.211.118.83
# basePath prefixes all resource paths 
basePath: /v1
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
################################################################################
#                                   Tags                                       #
################################################################################
tags:
  -
    name: "dashboard"
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  productnum:
    name: productnum
    in: path
    description: The product number
    type: number
  tag-name:
    name: tag-name
    in: path
    description: Tag name
    type: string  
################################################################################
#                                           Paths                              #
################################################################################  
paths:
  /getProductDetails:
    # binds a127 app logic to a route
    x-swagger-router-controller: ctl_dashboard
    get:
      tags:
        - "dashboard"   
      description: Returns consolidated dashboard data to the caller
      # used as the method name of the controller
      operationId: getProductDetails
      parameters:
        - name: productnum
          in: query
          description: The product num linked to the client
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ClientDashboardResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /client/{productnum}/dashboard:
    # binds a127 app logic to a route
    parameters:
      $ref: '#/parameters/productnum'    
    x-swagger-router-controller: ctl_dashboard
    get:
      tags:
        - "dashboard"   
      description: Returns consolidated dashboard data to the caller
      # used as the method name of the controller
      operationId: getProductDetails1
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ClientDashboardResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"            
  /ping:
    # binds a127 app logic to a route
    x-swagger-router-controller: ctl_ping
    get:
      tags:
        - "health"    
      description: Returns the health status of this service
      # used as the method name of the controller
      operationId: ping
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PingResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
################################################################################
#                                 Definitions                                  #
################################################################################
# complex objects have schema definitions
definitions:
  productdata:
      properties:
        product_id_num: 
          type: "integer"
        product_num: 
          type: "integer"
        product_type_cde:
          type: "integer"
        payment_amount: 
          type: "integer"
        payment_freq: 
          type: "string"
        owner_type_cde: 
          type: "integer"
        plan_txt: 
          type: "string"
        benefit_amt: 
          type: "integer"
        total_value: 
          type: "integer"
        dividend_amt: 
          type: "integer"
        loan_amt: 
          type: "integer"
      xml: 
        name: "Productdata"
  clientdata:
      properties:
        product_id_num: 
          type: "integer"
        client_id: 
          type: "integer"
        client_type_cde: 
          type: "integer"
        taxpayer_id: 
          type: "integer"
        first_name: 
          type: "string"
        middle_name: 
          type: "string"
        last_name: 
          type: "string"
        org_name: 
          type: "string"
        role_type_cde: 
          type: "integer"
        role_type_txt: 
          type: "string"
        email: 
          type: "string"
        birth_dte: 
          type: "string"
      xml: 
        name: "Clientdata"
  ClientDashboardResponse:
      properties:
        productinfo:
          type: "array"
          items:
            $ref: "#/definitions/productdata"
        clientinfo:
          type: "array"
          items:
            $ref: "#/definitions/clientdata"
      xml:
        name: "ClientDashboard"         
  PingResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
